### ISSUE TITLE
Profile Developer guide documentation

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#144]
Lets document how to write a profile, providing examples covering all of the different features available.
- Kustomize artifacts
- Helm artifacts
  - Helm values provided during installation time
  - Helm values defined in the profile definition
  - Local charts
  - Remote charts
- Nested profile artifacts
- Versioning (and how the catalog detects versions)

**Comment by Callisto13** [comment]
We have decided that for now (and perhaps for always 🤷‍♀️ ) we will put our docs on the new `profiles.dev` domain.

https://docusaurus.io/ is the hot new thing everyone is using, so let's go with that too to be consistent.

When writing the docs, let's try to very very clearly delineate the 3 different users we have:
- Profile author
- Catalog manager
- Profile user

**Comment by Callisto13** [comment]
- [x] intro and basics tutorial (https://github.com/weaveworks/profiles/pull/195)
  - the basics tutorial will deliberately leave out a lot of stuff and only talk about the bare minimum users need to begin
- [ ] highly detailed author docs
  - will include versioning etc
- [ ] highly detailed installer docs
  - will include pctl and catalog stuff
- [ ] catalog manager docs
- [ ] autogen pctl commands
- [ ] run all example snippets
- [ ] troubleshooting
- [ ] faqs
- [ ] advanced? 🤷‍♀️ 
- [ ] change logos and pics from the default
- [ ] replace all schemas with autogenerated one
- [ ] deploy somewhere

**Comment by Skarlso** [comment]
Please put any documentation things for profiles into https://github.com/weaveworks/profiles-userdocs/ from now on.
